/*
SQL 2025 :  ABORT_QUERY_EXECUTION 

*/

USE [MASTER]
GO
ALTER DATABASE [ADVENTUREWORKS2022] SET QUERY_STORE = ON
GO
ALTER DATABASE [ADVENTUREWORKS2022] SET QUERY_STORE (OPERATION_MODE = READ_WRITE)
GO

--- QUERY MOLESTA 

USE ADVENTUREWORKS2022 
GO

SELECT * FROM SALES.SALESORDERHEADER H
INNER JOIN 
SALES.SALESORDERDETAIL D
ON
D.SALESORDERID = H.SALESORDERID 

-- Vemos en QS 
-- NO TE DEJAMOS CORRER :-)

EXEC SYS.SP_QUERY_STORE_SET_HINTS
     @QUERY_ID = 40,
     @QUERY_HINTS = N'OPTION (USE HINT (''ABORT_QUERY_EXECUTION''))';

-- VOLVEMOS A PROBAR

SELECT * FROM SALES.SALESORDERHEADER H
INNER JOIN 
SALES.SALESORDERDETAIL D
ON
D.SALESORDERID = H.SALESORDERID 

-- VEMOS QUE QUERYS TIENEN HINTS

SELECT QUERY_HINT_ID,
    QUERY_ID,
    QUERY_HINT_TEXT,
    LAST_QUERY_HINT_FAILURE_REASON,
    LAST_QUERY_HINT_FAILURE_REASON_DESC,
    QUERY_HINT_FAILURE_COUNT,
    SOURCE,
    SOURCE_DESC
FROM SYS.QUERY_STORE_QUERY_HINTS

-- TE LIBERAMOS DE NUEVO
EXEC SYS.SP_QUERY_STORE_CLEAR_HINTS @QUERY_ID = 40;

-- VOLVEMOS A PROBAR

SELECT * FROM SALES.SALESORDERHEADER H
INNER JOIN 
SALES.SALESORDERDETAIL D
ON
D.SALESORDERID = H.SALESORDERID 