/*
SQL 2025 ACCELERATED_DATABASE_RECOVERY TEMPDB
*/

use tempdb
go

DROP TABLE IF EXISTS #DEMO2 

SELECT top 1000000
C.* 
INTO #DEMO2
FROM MASTER.SYS.COLUMNS C
CROSS JOIN MASTER.SYS.OBJECTS O1
CROSS JOIN MASTER.SYS.objects O2

BEGIN TRAN
 DELETE FROM #DEMO2

 ROLLBACK TRAN

-- Prendemos ADR en Tempdb

ALTER DATABASE TEMPDB SET ACCELERATED_DATABASE_RECOVERY = ON;

--PROBAMOS DE NUEVO

DROP TABLE IF EXISTS #DEMO2 

SELECT top 1000000
C.* 
INTO #DEMO2
FROM MASTER.SYS.COLUMNS C
CROSS JOIN MASTER.SYS.OBJECTS O1
CROSS JOIN MASTER.SYS.objects O2

BEGIN TRAN
 DELETE FROM #DEMO2

 ROLLBACK TRAN


SELECT NAME,is_accelerated_database_recovery_on 
FROM SYS.DATABASES

ALTER DATABASE TEMPDB SET ACCELERATED_DATABASE_RECOVERY = OFF;